version: '3.7'

services:
  postgres:
    image: postgres:12
    container_name: url_shortener_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=url_shortener
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - private_network

networks:
  private_network:

volumes:
  database:
