version: '3.7'

services:
  postgres:
    image: postgres:12
    container_name: url_shortener_postgres
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - private_network

networks:
  private_network:

volumes:
  database:
